// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using artari.entities;

#nullable disable

namespace artari.entities.Migrations
{
    [DbContext(typeof(ArtariDbContext))]
    [Migration("20250116180035_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("artari")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("artari.entities.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customer", "artari");
                });

            modelBuilder.Entity("artari.entities.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("PayOnDelivery")
                        .HasColumnType("bit");

                    b.Property<bool?>("PickupDelivery")
                        .HasColumnType("bit");

                    b.Property<long?>("TotalPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Order", "artari");
                });

            modelBuilder.Entity("artari.entities.Orders.OrderProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts", "artari");
                });

            modelBuilder.Entity("artari.entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cultivar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsNew")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSoldout")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Propagation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Species")
                        .HasColumnType("int");

                    b.Property<string>("SpeciesName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product", "artari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cultivar = "Bloodgood",
                            Description = "red leaves",
                            Height = "22",
                            ImageUrl = "img artar Bloodgood",
                            IsNew = false,
                            IsSoldout = false,
                            Name = "Acer palmatum Bloodgood",
                            Price = 55.0,
                            Priority = 1,
                            Propagation = "propagation details for Bloodgood",
                            Species = 0,
                            SpeciesName = "Palmatum",
                            Type = 0,
                            TypeName = "Acer"
                        },
                        new
                        {
                            Id = 2,
                            Cultivar = "Atropurpureum",
                            Description = "red leaves",
                            Height = "22",
                            ImageUrl = "img artar Atropurpureum",
                            IsNew = false,
                            IsSoldout = false,
                            Name = "Acer dissectum Atropurpureum",
                            Price = 58.0,
                            Priority = 2,
                            Propagation = "propagation details for Atropurpureum",
                            Species = 1,
                            SpeciesName = "Dissectum",
                            Type = 0,
                            TypeName = "Acer"
                        },
                        new
                        {
                            Id = 3,
                            Cultivar = "Green Cascade",
                            Description = "green leaves",
                            Height = "22",
                            ImageUrl = "img artar Green Cascade",
                            IsNew = false,
                            IsSoldout = false,
                            Name = "Acer japonicum Green Cascade",
                            Price = 12.800000000000001,
                            Priority = 1,
                            Propagation = "propagation details for Green Cascade",
                            Species = 3,
                            SpeciesName = "Japonicum",
                            Type = 0,
                            TypeName = "Acer"
                        });
                });

            modelBuilder.Entity("artari.entities.Orders.Order", b =>
                {
                    b.HasOne("artari.entities.Customers.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("artari.entities.Orders.OrderProducts", b =>
                {
                    b.HasOne("artari.entities.Orders.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("artari.entities.Products.Product", "Product")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("artari.entities.Customers.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("artari.entities.Orders.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("artari.entities.Products.Product", b =>
                {
                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
